### ISSUE TITLE
Build fails on downloading AnsiEsc.vba

### ISSUE THREAD

**Issue by dlobue** [lucc/nvimpager#13] opened 2019-06-06 09:56 UTC
FYI the build fails when fetching AnsiEsc. Here's the build output

```
sed 's#^RUNTIME=.*$#RUNTIME='"'/usr/share/nvimpager/runtime'"'#;s#version=.*$#version=v0.6-1-g205b59f#' < nvimpager > nvimpager.configured
chmod +x nvimpager.configured
curl https://www.drchip.org/astronaut/vim/vbafiles/AnsiEsc.vba.gz | \
  gunzip > AnsiEsc.vba
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 20599  100 20599    0     0  25029      0 --:--:-- --:--:-- --:--:-- 24998

gzip: stdin: unexpected end of file
make: *** [makefile:36: AnsiEsc.vba] Error 1
```

I am on archlinux and was attempting to install via the AUR.

I checked drchip's website, and it appears the package was updated on May 1st.

**Comment by lucc** [comment] 2019-06-06 13:13
It currently works for me. But it seems that the file was updated again: `Last-Modified: Mon, 27 May 2019 21:13:09 GMT`.  Can you please check if you can reproduce the error?

**Comment by lucc** [comment] 2019-09-29 21:37
I will close this, if there is an issue that we can work on, please reopen.

**Closed by lucc** 2019-09-29 21:37 UTC
